# File: wikitree.gpr.py
register(GRAMPLET,
         id="WikiTree",
         name=_("WikiTree"),
         description = _("WikiTree Integration"),
         version="0.1.0",
         gramps_target_version="6.0",
         status = STABLE,
         fname="wikitree.py",
         authors = ["Hans Boldt", "wquick", "Emma Connolly"],
         authors_email = [None, None, "emconnolly72@mailfence.com"],
         maintainers = ["Emma Connolly"],
         maintainers_email = ["emconnolly72@mailfence.com"],
         height = 50,
         detached_width = 400,
         detached_height = 500,
         gramplet = 'WikiTree',
         gramplet_title=_("WikiTree"),
         help_url="6.0_Addons#Addon_List",
         navtypes=['Person']
         )
